name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: rxjw95/rxjw95.github.io
          token: ${{ secrets.API_KEY}}
          ref: main
          username: rxjw95
      - run: git config --global user.email "rxjw95@gmail.com"
      - run: git config --global user.name "rxjw95"

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - if: steps.npm-cache.outputs.cache-hit == 'true'
        run: echo 'npm cache hit!'
      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: echo 'npm cache missed!'

      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1

      - name: npm install
        run: npm install --legacy-peer-deps

      - name: deploy
        run: npm run deploy-gh

